id: cff4df14b75a472d82e97bea40190937
initial_creation_type: ocr
source_metadata:
  volumes:
    e1d8141549dd4901a0158fa7be4deac1:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
